apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-docker-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-docker-project
  template:
    metadata:
      labels:
        app: my-docker-project
    spec:
      containers:
        - name: my-docker-project
          image: itheshtj/my_docker_project:latest
      imagePullSecrets:
        - name: regcred


